openweathermap.apiKey=${OPENWEATHER_API_KEY:}

mail.smtp.host=${MAIL_SMTP_HOST:smtp.gmail.com}
mail.smtp.port=${MAIL_SMTP_PORT:587}
mail.username=${MAIL_USERNAME:}
mail.password=${MAIL_PASSWORD:}
mail.from=${MAIL_FROM:${MAIL_USERNAME:}}